// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPwaZ6wx-qoS3cxiPlG3NGuiFdPQpRWCw',
    appId: '1:1075323028801:android:23812226223c064bd90dc0',
    messagingSenderId: '1075323028801',
    projectId: 'hukumpro-serverproxy-dev',
    databaseURL: 'https://hukumpro-serverproxy-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hukumpro-serverproxy-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH8gOqvm_RsLKbXF49LIVjzQRbfp4_oU8',
    appId: '1:1075323028801:ios:f134122c1ae098abd90dc0',
    messagingSenderId: '1075323028801',
    projectId: 'hukumpro-serverproxy-dev',
    databaseURL: 'https://hukumpro-serverproxy-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hukumpro-serverproxy-dev.appspot.com',
    iosBundleId: 'com.github.syafiqq.hukumpro',
  );
}
